name: deploy-ai_worker-prod

on:
  push:
    tags:
      - dev-*
      - stg-*
      - prod-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target_env:
        description: 'target environment [dev|stg|prod].'
        default: prod
        required: true

env:
  AWS_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        env:
          DEFAULT_TARGET_ENV: prod
        run: |
          export TAG_ENV=${ echo '${{github.ref}}' | sed -n -E 's/^refs\/tags\/(dev|stg|prod)-.*$/\1/p' }
          echo "TARGET_ENV=${{ github.event.inputs.target_env || $TAG_ENV || env.DEFAULT_TARGET_ENV }}" >> $GITHUB_ENV

      - name: ENV
        run: |
          echo $TARGET_ENV
