name: deploy-ai_worker-prod

on:
  push:
    tags:
      - dev-*
      - stg-*
      - prod-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target_env:
        description: 'target environment [dev|stg|prod].'
        default: prod
        required: true

env:
  AWS_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        env:
          DEFAULT_TARGET_ENV: prod
        run: |
          TAG_ENV=$(echo '${{github.ref}}' | sed -n -E 's/^refs\/tags\/(dev|stg|prod)-.*$/\1/p')
          echo $TAG_ENV
          if [ -n "$TAG_ENV" ]; then
            echo "TARGET_ENV=${{ github.event.inputs.target_env || env.TAG_ENV || env.DEFAULT_TARGET_ENV }}" >> $GITHUB_ENV
          else
            echo "TARGET_ENV=$TAG_ENV" >> $GITHUB_ENV
          fi

      - name: ENV
        run: |
          echo $TARGET_ENV
